### ISSUE TITLE
Meteor server console log error "Cannot set headers after they are sent to the client"

### ISSUE THREAD

**Issue by carlosalvidrez** [veliovgroup/ostrio#12]
Hi @dr-dimitru , wondering if this error message might tell you something. I'm a bit puzzled... perhaps something to do with your Meteor package "ostrio:spiderable-middleware"?

Thanks!

```
thf6m 08/05 10:44:11.070 AM onPageLoad: {"bot":"nobot","kind":"read","passage":"114cd!16","t":1731901,"ck":42,"agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"}
thf6m 08/05 10:44:12.472 AM [WARN] [Spiderable-Middleware] [REQ] ["aborted" event]: [Arguments] {}
thf6m 08/05 10:44:12.474 AM [WARN] [Spiderable-Middleware] [REQ] ["error" event] Unexpected error: Error: aborted
thf6m 08/05 10:44:12.474 AM     at abortIncoming (node:_http_server:794:17)
thf6m 08/05 10:44:12.474 AM     at socketOnClose (node:_http_server:788:3)
thf6m 08/05 10:44:12.474 AM     at Socket.emit (node:events:530:35)
thf6m 08/05 10:44:12.474 AM     at Socket.emit (node:domain:488:12)
thf6m 08/05 10:44:12.474 AM     at TCP.<anonymous> (node:net:337:12)
thf6m 08/05 10:44:12.474 AM     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
thf6m 08/05 10:44:12.474 AM   code: 'ECONNRESET'
thf6m 08/05 10:44:12.474 AM }
thf6m 08/05 10:44:12.474 AM Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
thf6m 08/05 10:44:12.474 AM     at ServerResponse.setHeader (node:_http_outgoing:659:11)
thf6m 08/05 10:44:12.474 AM     at contentSecurityPolicyMiddleware (/home/zcloud/app/programs/server/npm/node_modules/helmet/index.cjs:111:8)
thf6m 08/05 10:44:12.474 AM     at internalNext (/home/zcloud/app/programs/server/npm/node_modules/helmet/index.cjs:519:6)
thf6m 08/05 10:44:12.474 AM     at helmetMiddleware (/home/zcloud/app/programs/server/npm/node_modules/helmet/index.cjs:523:6)
thf6m 08/05 10:44:12.474 AM     at packages/montiapm:agent/lib/hijack/wrap_webapp.js:161:19
thf6m 08/05 10:44:12.474 AM     at AsyncLocalStorage.run (node:async_hooks:346:14)
thf6m 08/05 10:44:12.474 AM     at AwaitDetector.detect (/home/zcloud/app/programs/server/npm/node_modules/meteor/montiapm_agent/node_modules/@monti-apm/core/src/await-detector.ts:196:34)
thf6m 08/05 10:44:12.474 AM     at wrapper (packages/montiapm:agent/lib/hijack/wrap_webapp.js:160:42)
thf6m 08/05 10:44:12.474 AM     at packages/montiapm:agent/lib/hijack/wrap_webapp.js:174:14
thf6m 08/05 10:44:12.474 AM     at Layer.handle [as handle_request] (/home/zcloud/app/programs/server/npm/node_modules/meteor/webapp/node_modules/express/lib/router/layer.js:95:5)
thf6m 08/05 10:44:12.474 AM     at trim_prefix (/home/zcloud/app/programs/server/npm/node_modules/meteor/webapp/node_modules/express/lib/router/index.js:328:13)
thf6m 08/05 10:44:12.474 AM     at /home/zcloud/app/programs/server/npm/node_modules/meteor/webapp/node_modules/express/lib/router/index.js:286:9
thf6m 08/05 10:44:12.474 AM     at Function.process_params (/home/zcloud/app/programs/server/npm/node_modules/meteor/webapp/node_modules/express/lib/router/index.js:346:12)
thf6m 08/05 10:44:12.474 AM     at next (/home/zcloud/app/programs/server/npm/node_modules/meteor/webapp/node_modules/express/lib/router/index.js:280:10)
thf6m 08/05 10:44:12.474 AM     at IncomingMessage.<anonymous> (packages/ostrio:spiderable-middleware/lib/index.js:296:11)
thf6m 08/05 10:44:12.474 AM     at IncomingMessage.emit (node:events:518:28)
thf6m 08/05 10:44:12.474 AM     at IncomingMessage.emit (node:domain:488:12)
thf6m 08/05 10:44:12.474 AM     at emitErrorNT (node:internal/streams/destroy:169:8)
thf6m 08/05 10:44:12.474 AM     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
thf6m 08/05 10:44:12.474 AM     at processTicksAndRejections (node:internal/process/task_queues:82:21)
thf6m 08/05 10:44:40.114 AM /server/lib/onPageLoad in
thf6m 08/05 10:44:40.114 AM onPageLoad: {"bot":"petalbot","kind":"read","passage":"h2fh!3","t":796301,"ck":3,"agent":""}
```

**Comment by dr-dimitru** [comment]
Hello @carlosalvidrez ,

The quick guess — make sure "spiderable-middleware" registered __before__ all other "middleware listeners".

Was it working before? What's changed?

**Comment by carlosalvidrez** [comment]
Hi, I believe it works as I see many calls I suspect are coming from Otrio pre-render. Have changed many things so who knows. Will take a look at the server startup and see if I manage to figure it out. Thanks for the perspective!

**Comment by dr-dimitru** [comment]
@carlosalvidrez give it couple of days if it won't persist — feel free to close this issue as solved

**Comment by carlosalvidrez** [comment]
Thank you, I have pushed to prod ensuring your middleware runs first... we'll see. Closing this. Will open if it happens again and I can't figure it out : )
